FORMAT: 1A
HOST: http://timetables.maxmouchet.com/api

# VAMK Timetables API

# Group Courses
## Courses Collection [/courses.json]
### List all Courses [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Real Time Operating Systems"
            },
            {
                "id": 2,
                "name": "Finnish for Foreigners"
            }
        ]

# Group Groups
## Groups Collection [/courses/{id}/groups.json]
### List all Groups for a Course [GET]
+ Response 200 (application/json)

        ["I-IT-4N1", "I-IT-4N2"]

# Group Schedules
## Schedules Collection [/courses/{id}/schedules.json]
### List all Schedules for a Course [GET]
+ Response 200 (application/json)

        [
            {
                "id": 4090,
                "courseName": "Real Time Operating Systems",
                "startDateTime": "2014-01-13T06:15:00Z",
                "endDateTime": "2014-01-13T08:00:00Z",
                "professor": "JUMA",
                "room": "LEC4",
                "group": "I-IT-3N2"
            },
            {
                "id": 4091,
                "courseName": "Real Time Operating Systems",
                "startDateTime": "2014-01-17T06:15:00Z",
                "endDateTime": "2014-01-17T09:45:00Z",
                "professor": "JUMA",
                "room": "LEC4",
                "group": "I-IT-3N2"
            }
        ]

