source 'https://rubygems.org'

ruby '2.0.0'

gem 'unicorn', '~> 4.6.3'
gem 'foreman', '~> 0.63.0'

gem 'sinatra', '~> 1.4.4'
gem 'sinatra-contrib', '~> 1.4.1'
gem 'sinatra-cross_origin', '~> 0.2.0'

gem 'pg', '~> 0.17.0'
